export const FETCH_APPLICATIONS = 'FETCH_APPLICATIONS';
export const FETCH_APPLICATIONS_PENDING = 'FETCH_APPLICATIONS_PENDING';
export const FETCH_APPLICATIONS_REJECTED = 'FETCH_APPLICATIONS_REJECTED';
export const FETCH_APPLICATIONS_FULFILLED = 'FETCH_APPLICATIONS_FULFILLED';

export const CREATE_APPLICATION = 'CREATE_APPLICATION';

export const FETCH_PERMISSIONS = 'FETCH_PERMISSIONS';
export const FETCH_PERMISSIONS_PENDING = 'FETCH_PERMISSIONS_PENDING';
export const FETCH_PERMISSIONS_REJECTED = 'FETCH_PERMISSIONS_REJECTED';
export const FETCH_PERMISSIONS_FULFILLED = 'FETCH_PERMISSIONS_FULFILLED';

export const SAVE_PERMISSION = 'SAVE_PERMISSION';
export const SAVE_PERMISSION_PENDING = 'SAVE_PERMISSION_PENDING';
export const SAVE_PERMISSION_REJECTED = 'SAVE_PERMISSION_REJECTED';
export const SAVE_PERMISSION_FULFILLED = 'SAVE_PERMISSION_FULFILLED';

export const CANCEL_USER_PICKER = 'CANCEL_USER_PICKER';
export const CONFIRM_USER_PICKER = 'CONFIRM_USER_PICKER';
export const OPEN_USER_PICKER = 'OPEN_USER_PICKER';
export const OPEN_USER_PICKER_PENDING = 'OPEN_USER_PICKER_PENDING';
export const OPEN_USER_PICKER_REJECTED = 'OPEN_USER_PICKER_REJECTED';
export const OPEN_USER_PICKER_FULFILLED = 'OPEN_USER_PICKER_FULFILLED';

export const SELECT_USER = 'SELECT_USER';
export const UNSELECT_USER = 'UNSELECT_USER';

export const CREATE_PERMISSION = 'CREATE_PERMISSION';
export const EDIT_PERMISSION = 'SAVE_PERMISSION';
export const CLEAR_PERMISSION = 'CLEAR_PERMISSION';

export const REQUESTING_DELETE_PERMISSION = 'REQUESTING_DELETE_PERMISSION';
export const CANCEL_DELETE_PERMISSION = 'CANCEL_DELETE_PERMISSION';
export const DELETE_PERMISSION = 'DELETE_PERMISSION';
export const DELETE_PERMISSION_PENDING = 'DELETE_PERMISSION_PENDING';
export const DELETE_PERMISSION_REJECTED = 'DELETE_PERMISSION_REJECTED';
export const DELETE_PERMISSION_FULFILLED = 'DELETE_PERMISSION_FULFILLED';

export const ADD_GROUP_MEMBERS = 'ADD_GROUP_MEMBERS';
export const ADD_GROUP_MEMBERS_PENDING = 'ADD_GROUP_MEMBERS_PENDING';
export const ADD_GROUP_MEMBERS_REJECTED = 'ADD_GROUP_MEMBERS_REJECTED';
export const ADD_GROUP_MEMBERS_FULFILLED = 'ADD_GROUP_MEMBERS_FULFILLED';

export const REMOVE_GROUP_MEMBERS = 'REMOVE_GROUP_MEMBERS';
export const REMOVE_GROUP_MEMBERS_PENDING = 'REMOVE_GROUP_MEMBERS_PENDING';
export const REMOVE_GROUP_MEMBERS_REJECTED = 'REMOVE_GROUP_MEMBERS_REJECTED';
export const REMOVE_GROUP_MEMBERS_FULFILLED = 'REMOVE_GROUP_MEMBERS_FULFILLED';

export const FETCH_ROLES = 'FETCH_ROLES';
export const FETCH_ROLES_PENDING = 'FETCH_ROLES_PENDING';
export const FETCH_ROLES_REJECTED = 'FETCH_ROLES_REJECTED';
export const FETCH_ROLES_FULFILLED = 'FETCH_ROLES_FULFILLED';

export const SAVE_ROLE = 'SAVE_ROLE';
export const SAVE_ROLE_PENDING = 'SAVE_ROLE_PENDING';
export const SAVE_ROLE_REJECTED = 'SAVE_ROLE_REJECTED';
export const SAVE_ROLE_FULFILLED = 'SAVE_ROLE_FULFILLED';

export const CREATE_ROLE = 'CREATE_ROLE';
export const EDIT_ROLE = 'SAVE_ROLE';
export const CLEAR_ROLE = 'CLEAR_ROLE';

export const REQUESTING_DELETE_ROLE = 'REQUESTING_DELETE_ROLE';
export const CANCEL_DELETE_ROLE = 'CANCEL_DELETE_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';
export const DELETE_ROLE_PENDING = 'DELETE_ROLE_PENDING';
export const DELETE_ROLE_REJECTED = 'DELETE_ROLE_REJECTED';
export const DELETE_ROLE_FULFILLED = 'DELETE_ROLE_FULFILLED';

export const FETCH_GROUPS = 'FETCH_GROUPS';
export const FETCH_GROUPS_PENDING = 'FETCH_GROUPS_PENDING';
export const FETCH_GROUPS_REJECTED = 'FETCH_GROUPS_REJECTED';
export const FETCH_GROUPS_FULFILLED = 'FETCH_GROUPS_FULFILLED';

export const FETCH_GROUP = 'FETCH_GROUP';
export const FETCH_GROUP_PENDING = 'FETCH_GROUP_PENDING';
export const FETCH_GROUP_REJECTED = 'FETCH_GROUP_REJECTED';
export const FETCH_GROUP_FULFILLED = 'FETCH_GROUP_FULFILLED';

export const FETCH_GROUP_MEMBERS = 'FETCH_GROUP_MEMBERS';
export const FETCH_GROUP_MEMBERS_PENDING = 'FETCH_GROUP_MEMBERS_PENDING';
export const FETCH_GROUP_MEMBERS_REJECTED = 'FETCH_GROUP_MEMBERS_REJECTED';
export const FETCH_GROUP_MEMBERS_FULFILLED = 'FETCH_GROUP_MEMBERS_FULFILLED';

export const SAVE_GROUP = 'SAVE_GROUP';
export const SAVE_GROUP_PENDING = 'SAVE_GROUP_PENDING';
export const SAVE_GROUP_REJECTED = 'SAVE_GROUP_REJECTED';
export const SAVE_GROUP_FULFILLED = 'SAVE_GROUP_FULFILLED';

export const CREATE_GROUP = 'CREATE_GROUP';
export const EDIT_GROUP = 'EDIT_GROUP';
export const CLEAR_GROUP = 'CLEAR_GROUP';

export const REQUESTING_DELETE_GROUP = 'REQUESTING_DELETE_GROUP';
export const CANCEL_DELETE_GROUP = 'CANCEL_DELETE_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const DELETE_GROUP_PENDING = 'DELETE_GROUP_PENDING';
export const DELETE_GROUP_REJECTED = 'DELETE_GROUP_REJECTED';
export const DELETE_GROUP_FULFILLED = 'DELETE_GROUP_FULFILLED';

export const FETCH_LOGS = 'FETCH_LOGS';
export const FETCH_LOGS_PENDING = 'FETCH_LOGS_PENDING';
export const FETCH_LOGS_REJECTED = 'FETCH_LOGS_REJECTED';
export const FETCH_LOGS_FULFILLED = 'FETCH_LOGS_FULFILLED';

export const FETCH_LOG = 'FETCH_LOG';
export const FETCH_LOG_PENDING = 'FETCH_LOG_PENDING';
export const FETCH_LOG_REJECTED = 'FETCH_LOG_REJECTED';
export const FETCH_LOG_FULFILLED = 'FETCH_LOG_FULFILLED';

export const CLEAR_LOG = 'CLEAR_LOG';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING';
export const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED';
export const FETCH_USERS_FULFILLED = 'FETCH_USERS_FULFILLED';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_PENDING = 'FETCH_USER_PENDING';
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';

export const FETCH_USER_LOGS = 'FETCH_USER_LOGS';
export const FETCH_USER_LOGS_PENDING = 'FETCH_USER_LOGS_PENDING';
export const FETCH_USER_LOGS_REJECTED = 'FETCH_USER_LOGS_REJECTED';
export const FETCH_USER_LOGS_FULFILLED = 'FETCH_USER_LOGS_FULFILLED';

export const FETCH_USER_DEVICES = 'FETCH_USER_DEVICES';
export const FETCH_USER_DEVICES_PENDING = 'FETCH_USER_DEVICES_PENDING';
export const FETCH_USER_DEVICES_REJECTED = 'FETCH_USER_DEVICES_REJECTED';
export const FETCH_USER_DEVICES_FULFILLED = 'FETCH_USER_DEVICES_FULFILLED';

export const REQUESTING_REMOVE_MULTIFACTOR = 'REQUESTING_REMOVE_MULTIFACTOR';
export const CANCEL_REMOVE_MULTIFACTOR = 'CANCEL_REMOVE_MULTIFACTOR';
export const REMOVE_MULTIFACTOR = 'REMOVE_MULTIFACTOR';
export const REMOVE_MULTIFACTOR_PENDING = 'REMOVE_MULTIFACTOR_PENDING';
export const REMOVE_MULTIFACTOR_REJECTED = 'REMOVE_MULTIFACTOR_REJECTED';
export const REMOVE_MULTIFACTOR_FULFILLED = 'REMOVE_MULTIFACTOR_FULFILLED';

export const REQUESTING_BLOCK_USER = 'REQUESTING_BLOCK_USER';
export const CANCEL_BLOCK_USER = 'CANCEL_BLOCK_USER';
export const BLOCK_USER = 'BLOCK_USER';
export const BLOCK_USER_PENDING = 'BLOCK_USER_PENDING';
export const BLOCK_USER_REJECTED = 'BLOCK_USER_REJECTED';
export const BLOCK_USER_FULFILLED = 'BLOCK_USER_FULFILLED';

export const REQUESTING_UNBLOCK_USER = 'REQUESTING_UNBLOCK_USER';
export const CANCEL_UNBLOCK_USER = 'CANCEL_UNBLOCK_USER';
export const UNBLOCK_USER = 'UNBLOCK_USER';
export const UNBLOCK_USER_PENDING = 'UNBLOCK_USER_PENDING';
export const UNBLOCK_USER_REJECTED = 'UNBLOCK_USER_REJECTED';
export const UNBLOCK_USER_FULFILLED = 'UNBLOCK_USER_FULFILLED';

export const SHOW_LOGIN = 'SHOW_LOGIN';
export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';

export const LOADED_TOKEN = 'LOADED_TOKEN';
export const RECIEVED_TOKEN = 'RECIEVED_TOKEN';

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
