module.exports = `/*
*  This rule been automatically generated by auth0-authz-extension
*  Updated by <%= userName %>, <%= updateTime() %>
 */
async function (user, context, callback) {
  var EXTENSION_URL = "<%= extensionUrl %>";

  var audience = '';
  audience = audience || (context.request && context.request.query && context.request.query.audience);
  if (audience === 'urn:auth0-authz-api') {
    return callback(new UnauthorizedError('no_end_users'));
  }

  audience = audience || (context.request && context.request.body && context.request.body.audience);
  if (audience === 'urn:auth0-authz-api') {
    return callback(new UnauthorizedError('no_end_users'));
  }

  // Convert groups to array
  function parseGroups(data) {
    if (typeof data === 'string') {
      // split groups represented as string by spaces and/or comma
      return data.replace(/,/g, ' ').replace(/\\s+/g, ' ').split(' ');
    }
    return data;
  }

  // Get the policy for the user.
  function getPolicy(user, context) {
    return new Promise((resolve, reject) => {
      request.post({
        url: EXTENSION_URL + "/api/users/" + user.user_id + "/policy/" + context.clientID,
        headers: {
          "x-api-key": configuration.AUTHZ_EXT_API_KEY
        },
        json: {
          connectionName: context.connection || user.identities[0].connection,
          groups: parseGroups(user.groups)
        },
        timeout: 5000
      }, (err, res, data) => {
        if (err) return reject(err);
        resolve({ res, data });
      });
    });
  }<% if (config.persistGroups || config.persistRoles || config.persistPermissions) { %>

  // Store authorization data in the user profile so we can query it later.
  async function saveToMetadata(user, groups, roles, permissions) {
    user.app_metadata = user.app_metadata || {};
    user.app_metadata.authorization = {<% if (config.persistGroups && !config.groupsPassthrough) { %>
      groups: groups,<% } %><% if (config.persistGroups && config.groupsPassthrough) { %>
      groups: mergeRecords(user.groups, groups),<% } %><% if (config.persistRoles && !config.rolesPassthrough) { %>
      roles: roles,<% } %><% if (config.persistRoles && config.rolesPassthrough) { %>
      roles: mergeRecords(user.roles, roles),<% } %><% if (config.persistPermissions && !config.permissionsPassthrough) { %>
      permissions: permissions<% } %><% if (config.persistPermissions && config.permissionsPassthrough) { %>
      permissions: mergeRecords(user.permissions, permissions)<% } %>
    };

    await auth0.users.updateAppMetadata(user.user_id, user.app_metadata);
  }<% } %><% if (config.groupsPassthrough || config.rolesPassthrough || config.permissionsPassthrough) { %>

  // Merge the IdP records with the records of the extension.
  function mergeRecords(idpRecords, extensionRecords) {
    idpRecords = idpRecords || [];
    extensionRecords = extensionRecords || [];

    if (!Array.isArray(idpRecords)) {
      idpRecords = idpRecords.replace(/,/g, ' ').replace(/\\s+/g, ' ').split(' ');
    }

    return [...new Set([...idpRecords, ...extensionRecords])];
  }<% } %>

  try {
    const { res, data } = await getPolicy(user, context);

    if (res.statusCode !== 200) {
      console.log('Error from Authorization Extension:', res.body || res.statusCode);
      return callback(
        new UnauthorizedError('Authorization Extension: ' + ((res.body && (res.body.message || res.body)) || res.statusCode))
      );
    }

    // Update the user object.<% if (config.groupsInToken && !config.groupsPassthrough) { %>
    user.groups = data.groups;<% } %><% if (config.groupsInToken && config.groupsPassthrough) { %>
    user.groups = mergeRecords(user.groups, data.groups);<% } %><% if (config.rolesInToken && !config.rolesPassthrough) { %>
    user.roles = data.roles;<% } %><% if (config.rolesInToken && config.rolesPassthrough) { %>
    user.roles = mergeRecords(user.roles, data.roles);<% } %><% if (config.permissionsInToken && !config.permissionsPassthrough) { %>
    user.permissions = data.permissions;<% } %><% if (config.permissionsInToken && config.permissionsPassthrough) { %>
    user.permissions = mergeRecords(user.permissions, data.permissions);<% } %>

<% if (config.persistGroups || config.persistRoles || config.persistPermissions) { %>
    await saveToMetadata(user, data.groups, data.roles, data.permissions);
<% } %>

return callback(null, user, context);
  } catch (err) {
    console.log('Error from Authorization Extension:', err);
    return callback(new UnauthorizedError('Authorization Extension: ' + err.message));
  }
}`;
