module.exports = `/*
*  This rule been automatically generated by auth0-authz-extension
*  Updated by <%= userName %>, <%= updateTime() %>
*/
function (user, context, callback) {
  var audience = "";
  audience = audience || (context.request.query && context.request.query.audience);
  audience = audience || (context.request.body && context.request.body.audience);

  if (audience === "urn:auth0-authz-api") {
    return callback(new UnauthorizedError("no_end_users"));
  }
  callback(null, user, context);
}`